services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - ./chromadb:/data
    ports:
      - "8765:8000"